### ISSUE TITLE
front - main - posting

### ISSUE THREAD

**Issue by gondoc** [Team-WNY/Issue#14]
글 작성 modal popup 
---

1. 게시글 사진 연동 처리 및 사진 가져오기 처리 
2. 여러 사진일 경우에 대한 예외처리 
3. 주소 - 주소 api 다음, 카카오 이용관련 확인 요망 / pin 처리 가능한 api 확인 요망.
4. x 버튼 누를 경우 confirm() 있어야 함. 기존 작성 중이던 내용은 사라집니다. 이 창을 닫으시겠습니까? Y / N 띄울 것.
  y: modal popup fade out and modal popup data initialize / n: cancel
5. AM I / HELP 글 작성 관련 컴포넌트 공용처리할 것 .

- 이 창을 닫으시겠습니까? 컴포넌트 추가 제작?
기획팀 상의사항 @siloamliky 

---

![image](https://github.com/Team-WNY/Issue/assets/94984063/6a774bfa-a704-4d5e-abe1-d6b85b31ebd6)

![image](https://github.com/Team-WNY/Issue/assets/94984063/8b7f12ec-f6c4-4d11-8ab4-23a68fe04273)

**Comment by siloamliky** [comment]
문의하신 내용
--
지난 회의때에 취소 버튼 (x) 버튼 클릭시 화면이 닫혀지기 전에 
이 창을 닫으시겠습니까? y/n 알림창을 띄우게 하자 라고 소결론이 났던 것이라 같은데, 해당 확인yn 컴포넌트는 없는 것 같아서 확인차 질문 드렸습니다.

기본 y/n 으로 띄울 수는 있겠지만, 
미관상 좋지는 않을 거라 (css가 깨질 수도 있구요… 깨지는지 여부는 개발 및 적용해봐야 알 것 같습니다. 확답을 못드리는 상황에서 판단해달라고 말씀 드려 송구합니다요…) 

맘 같아서는 확인 취소 버튼이 있는 확인 전용 모달 컴포넌트 하나 만들어 주십사 하는데, 
만약 여의치 않다면 기본으로도 가능합니다. 

해당 부분 관련해서 기본으로 처리할지 컴포넌트를 추가 제작해주시는지 확인차 질문 드렸었습니다. 

문의에 대한 답변
--
별도의 모달 제작 완료.
피그마 참조(https://www.figma.com/file/F9rsLPXeJg1eS9lO09YP7q/iny?type=design&node-id=0%3A1&mode=design&t=VAmnds8ojSExN2RQ-1)
