### ISSUE TITLE
화면 정의서 작성 및 요구사항 정의서 구체화 / 기초 플로우 차트 작성

### ISSUE THREAD

**Issue by CASY82** [Team-WNY/Issue#6]

**Comment by siloamliky** [comment]
20230723 기획팀 화면정의서 초안 작성 및 요구사항 정의서 구체화

**Comment by siloamliky** [comment]
20230818 기획팀 화면정의서 초안 작성완료

**Comment by siloamliky** [comment]
화면정의서 초안(구글 슬라이드) : https://docs.google.com/presentation/d/1Xr4aMRXZ1qwNhjZA3HFGN8Wq4t8Ilfwq8wC3pzAbF3Y/edit?usp=sharing
화면정의서 개발버전(피그마) : https://www.figma.com/file/F9rsLPXeJg1eS9lO09YP7q/component?type=design&node-id=0%3A1&mode=design&t=k7Q2Fj4PXhXqmnd3-1
