### ISSUE TITLE
Account 도메인 개발 진행

### ISSUE THREAD

**Issue by CASY82** [Team-WNY/Issue#7]

**Comment by siloamliky** [comment]
계정 데이터셋 가짓수
1. 아이디
2. 비밀번호
3. 이름
4. 닉네임
5. 생년월일
6. 이메일
7. 연락처
8. 주소
9. 빨강하트
10. 검정하트
11. 팔로워
12. 팔로잉
13. 업로드 한 ami 갯수합

**Comment by CASY82** [comment]
도메인 하트 기능 제외하고 1차 개발 완료
